@echo off

set ROOT_DIR=%~dp0
if "%ROOT_DIR%" == "" set ROOT_DIR=.
set APP_BASE_NAME=%~n0
set APP_HOME=%ROOT_DIR%

SET ELASTIC_ROOT=%ROOT_DIR%elasticsearch-6.0.0-beta1\bin
SET KIBANA_ROOT=%ROOT_DIR%kibana-6.0.0-beta1\bin
SET FILEBEAT_ROOT=%ROOT_DIR%filebeat

SET LOGSTASH_ROOT=%ROOT_DIR%logstash\bin
REM SET LOGSTASH_CONFIG=%ROOT_DIR%config\logstash-jdbc.conf
SET LOGSTASH_CONFIG=%ROOT_DIR%config\logstash.conf

SET KAFKA_ROOT=%ROOT_DIR%kafka
SET ZOOKEEPER_ROOT=%ROOT_DIR%zookeeper


echo ROOT_DIR: %ROOT_DIR%
echo ELASTIC_ROOT: %ELASTIC_ROOT%
echo KIBANA_ROOT: %KIBANA_ROOT%
echo FILEBEAT_ROOT: %FILEBEAT_ROOT%
echo LOGSTASH_ROOT: %LOGSTASH_ROOT%
echo LOGSTASH_CONFIG: %LOGSTASH_CONFIG%
echo KAFKA_ROOT: %KAFKA_ROOT%
echo ZOOKEEPER_ROOT: %ZOOKEEPER_ROOT%